import { IconType } from 'react-icons';
import { FaApple, FaEnvelope, FaGithub, FaJs, FaLinkedin } from 'react-icons/fa';
import { 
  SiTypescript, 
  SiExpress, 
  SiNodedotjs, 
  SiMongodb, 
  SiSocketdotio, 
  SiReact, 
  SiWebgl, 
  SiSharp, 
  SiUnity, 
  SiVuedotjs,
  SiTailwindcss, 
  SiHtml5, 
  SiCss3, 
  SiSwift, 
  SiFirebase, 
  SiLinux, 
  SiPython,
  SiC,
  SiCplusplus,
  SiJson,
  SiRedux,
  SiJest,
  SiPostman,
  SiGit,
  SiXcode,
  SiUbuntu,
  SiRedhat,
  SiApple,
  SiAssemblyscript,
  SiCocoapods
} from 'react-icons/si';


const iconMap: Record<string, IconType> = {
  'TypeScript': SiTypescript,
  'Express': SiExpress,
  'Node.js': SiNodedotjs,
  'MongoDB': SiMongodb,
  'Socket.io': SiSocketdotio,
  'React': SiReact,
  'WebGL': SiWebgl,
  'C#': SiSharp,
  'Unity': SiUnity,
  'Vue.js': SiVuedotjs,
  'Tailwind': SiTailwindcss,
  'HTML': SiHtml5,
  'CSS': SiCss3,
  'Swift': SiSwift,
  'Firebase': SiFirebase,
  'Linux': SiLinux,
  'Python': SiPython,
  'C': SiC,
  'C++': SiCplusplus,
  'JSON': SiJson,
  'FUSE': SiLinux,
  'Redux': SiRedux,
  'Jest': SiJest,
  'Postman': SiPostman,
  'Git': SiGit,
  'Xcode': SiXcode,
  'Ubuntu': SiUbuntu,
  'RedHat': SiRedhat,
  'Apple': SiApple,
  'Csharp': SiSharp,
  'Assemblyscript': SiAssemblyscript,
  'CocoaPods': SiCocoapods,
  'Github': FaGithub,
  'Linkedin': FaLinkedin,
  'Envelope': FaEnvelope,
  'JavaScript': FaJs,
  'UIKit': FaApple,
  'SwiftUI': FaApple,
  'Core Data': FaApple,
  'Core ML': FaApple,
  'pytest': SiPython,
  'REST APIs': SiPostman,
  'CoreData': SiApple,
  'Objective-C': SiApple,
  'Assembly': SiAssemblyscript


};

export const getTechIcon = (tech: string): IconType | null => {
  return iconMap[tech] || null;
}; 